inherit_from: .rubocop_ffi-openmpt.yml

# Turn this off for now. CI checks different versions of ruby anyway.
Gemspec/RequiredRubyVersion:
  Exclude:
    - 'ffi-openmpt.gemspec'

# Force ruby19 style hash keys, but be consistent within a hash.
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
