inherit_from: .rubocop_ffi-openmpt.yml

# Turn this off for now. CI checks different versions of ruby anyway.
Gemspec/RequiredRubyVersion:
  Exclude:
    - 'ffi-openmpt.gemspec'

# Force ruby19 style hash keys, but be consistent within a hash.
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

# Enforce empty lines at the beginning of classes.
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: beginning_only

# Allow empty lines, or not, around module bodies. I like a line at the
# beginning, but not the end, but this is not an option in RuboCop.
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Allow compact child definitions in the tests for brevity.
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'
