inherit_from: .rubocop_ffi-openmpt.yml

# Turn this off for now. CI checks different versions of ruby anyway.
Gemspec/RequiredRubyVersion:
  Exclude:
    - 'ffi-openmpt.gemspec'

# Force ruby19 style hash keys, but be consistent within a hash.
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

# Use brackets style for symbol arrays.
Style/SymbolArray:
  EnforcedStyle: brackets

# Enforce empty lines at the beginning of classes.
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: beginning_only

# Allow empty lines, or not, around module bodies. I like a line at the
# beginning, but not the end, but this is not an option in RuboCop.
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Don't enforce things like #positive? due to older rubies not supporting it
Style/NumericPredicate:
  EnforcedStyle: comparison

# Allow compact child definitions in the tests for brevity.
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'

# Ignore ABC failures in the tests.
Metrics/AbcSize:
  Exclude:
    - 'test/**/*.rb'

# Set a more reasonable method length and ignore failures in the tests.
Metrics/MethodLength:
  Exclude:
    - 'test/**/*.rb'

# Set a more reasonable class length and ignore failures in the tests.
Metrics/ClassLength:
  Exclude:
    - 'test/**/*.rb'

# Set a more reasonable module length and ignore failures in the tests.
Metrics/ModuleLength:
  Exclude:
    - 'test/**/*.rb'

# Set a more reasonable block length and ignore failures in the tests.
Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'
