require: rubocop-performance

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

# Enforce empty lines at the beginning of classes.
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: beginning_only

# Allow empty lines, or not, around module bodies. I like a line at the
# beginning, but not the end, but this is not an option in RuboCop.
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Ignore ABC failures in the tests.
Metrics/AbcSize:
  Exclude:
    - 'test/**/*.rb'

# Ignore block length failures in the tests.
Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'

# Set a more reasonable class length and ignore failures in the tests.
Metrics/ClassLength:
  Max: 250
  Exclude:
    - 'test/**/*.rb'

# Set a more reasonable method length and ignore failures in the tests.
Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'test/**/*.rb'

# Set a more reasonable module length and ignore failures in the tests.
# Also allow the API module to be very long as it just maps lots of methods.
Metrics/ModuleLength:
  Exclude:
    - 'lib/ffi/openmpt/api.rb'
    - 'test/**/*.rb'

# Allow compact child definitions in the tests for brevity.
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'

Style/MixinUsage:
  Exclude:
    - 'examples/**/*'

# Use brackets style for symbol arrays.
Style/SymbolArray:
  EnforcedStyle: brackets
