language: ruby

sudo: false

cache: bundler

addons:
  apt:
    packages:
      - libopenmpt

rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - rbx-3
  - ruby-head

matrix:
  allow_failures:
    - rvm: rbx-3
    - rvm: ruby-head

before_install: gem install bundler -v 1.16.1
