language: ruby

sudo: required

cache: bundler

before_install:
  - gem install bundler -v 1.16.1
  - sudo apt-get install -y libopenmpt

rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - rbx-3
  - ruby-head

matrix:
  allow_failures:
    - rvm: rbx-3
    - rvm: ruby-head
