dist: xenial
language: ruby

cache: bundler

before_install:
  - gem install bundler -v 2.0.1
  - ./test/install-libopenmpt.sh
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR/usr/lib

rvm:
  - 2.4.5
  - 2.5.5
  - 2.6.2
  - rbx-3
  - ruby-head

env:
  - TEST_LIBOPENMPT_VERSION=0.3.11
  - TEST_LIBOPENMPT_VERSION=0.3.12

matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-3
    - rvm: ruby-head
    - env: TEST_LIBOPENMPT_VERSION=0.3.12
  exclude:
    - rvm: rbx-3
      env: TEST_LIBOPENMPT_VERSION=0.3.12
