language: ruby

sudo: false

cache: bundler

before_install:
  - gem install bundler -v 1.16.1
  - ./test/install-libopenmpt.sh
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR/usr/lib

rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - rbx-3
  - ruby-head

matrix:
  allow_failures:
    - rvm: rbx-3
    - rvm: ruby-head
