dist: xenial
language: ruby

cache: bundler

before_install:
  - gem install bundler -v 2.1
  - ./test/install-libopenmpt.sh
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR/usr/lib
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/usr/bin

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - rbx-4
  - truffleruby
  - ruby-head

env:
  - TEST_LIBOPENMPT_VERSION=0.3.12
  - TEST_LIBOPENMPT_VERSION=0.5.1

matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-4
    - rvm: truffleruby
    - rvm: ruby-head
  exclude:
    - rvm: rbx-4
      env: TEST_LIBOPENMPT_VERSION=0.3.12
    - rvm: truffleruby
      env: TEST_LIBOPENMPT_VERSION=0.3.12
